# Generated by Django 4.2 on 2023-07-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField(verbose_name='Xabar Id')),
                ('need_why', models.CharField(max_length=50, verbose_name='Bizga kerak')),
                ('texnologies', models.CharField(max_length=300, verbose_name='Texnalogiyalar')),
                ('location', models.CharField(max_length=100, verbose_name='Joylashuv')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
                'db_table': 'contents',
                'managed': True,
            },
        ),
    ]
