# Generated by Django 4.2 on 2023-07-30 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cotent',
            new_name='Content',
        ),
    ]
